config/routes.rb
Gpathome::Application.routes.draw do

  # ActiveAdmin routes
  ActiveAdmin.routes(self)

  # devise setup for users
  # redirect after sign up
  # see: http://stackoverflow.com/questions/3827011/devise-custom-routes-and-login-pages
  devise_for :users, :controllers => { :registrations => 'registrations', :invitations => 'invitations' },
  :path => '',
  :path_names => { :sign_in => 'login', :sign_out => 'logout', :sign_up => 'sign_up' }

  # scope for devise routes
  devise_scope :user do
    match 'payment' => 'registrations#payment'
    match 'confirm' => 'registrations#confirm'
    match 'accepted' => 'invitations#accepted'
  end

  # on successful login
  namespace :user do
    root :to => 'dashboard#index'
  end

  resource :user do
    # user credits (top up etc)
    resources :credits do
      member do
        post 'top_up'
      end
    end
    # user account - what plan they are on, payments, expiration dates etc
    resource :account do
      member do
        get 'billing_details'
      end
      resource :password
      resource :notification
      resource :group
    end
  end

  get '/user/docustore' => 'docustore#index', :as => :docustore

  # path to upgrade current plan
  post '/plan/switch' => 'plans#switch', :as => :switch_plan

  # dependent profiles
  resources :profiles
  resources :medical_profiles

  # add the put method to /user/profile/edit for the user profiles page under the dashboard
  put '/user/account/password/edit', :as => :edit_user_account_password, :to => 'passwords#update'

  # check for new messages - via ajax
  get '/check_for_messages' => 'messages#check_for_messages'

  # user feedback
  resource :feedback

  # add the put method to /user/profile/edit for the user profiles page under the dashboard, do the same for medical profiles
  put '/profiles/:id/edit', :as => :edit_profile, :to => 'profiles#update'
  put '/medical_profiles/:id/edit', :as => :edit_medical_profile, :to => 'medical_profiles#update'

  # devise for admins
  #devise_for :admin_users, ActiveAdmin::Devise.config

  # assets
  resources :assets

  slugs = %w(take_a_tour our_service terms_and_conditions faqs typical_scenarios contact_us about_us)
  slugs.each do |slug|
    get "#{slug}_raw" => "static##{slug}", as: slug
  end

  get ':slug', to: 'pages#show',
    constraints: ->(req){ slugs.include? req.params[:slug] },
    as: :pages

  # main user dashbaord
  get 'dashboard' => 'dashboard#index'

  # static routes
  if SHOW_MEMBERSHIP_PLANS
    get 'membership_plans' => 'static#membership_plans'
  end
  post 'request_invite' => 'static#request_invite'

  resources :consultations do
    resources :messages
  end

  # payments - recurly
  namespace :payments do
    get 'success'
  end

  # currently routing to static / index
  root :to => 'static#index'

end

app/models/group.rb
class Group < ActiveRecord::Base

  # Group belongs to a plan
  # Reason: because the group will share the plans credits etc
  # Example: Couple plan, one admin of the group and a regular user,
  # both sharing plan credits
  belongs_to :plan

  belongs_to :admin, class_name: 'User', foreign_key: 'admin_id'

  # Group has many users
  # one of which will be the admin for the group (only one account holder)
  has_many :users

  has_many :account_credits

  attr_accessible :user_attributes, :admin_id, :plan_id, :group_type

  accepts_nested_attributes_for :users, :account_credits

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  # check whoever it is has access to groups
  load_and_authorize_resource

  before_filter :find_group

  def show
  end

  private

    def find_group
      @group = current_user.group
    end

end

app/views/groups/show.html.haml
- title('Account Users')

.row-fluid.dashboard-main
  .span8.main

    = render :partial => 'layouts/account_nav_header'

    .row-fluid
      .span12
        %h2 Account Users
        %p Below is a list of other users of your account&hellip;

        %p
          You are currently on the
          %b= current_user.group.plan.name
          plan and can add a further
          %b= current_user.group_users_remaining?
          users to your account.

        - if current_user.group.plan.name == 'Family'
          %p
            When you click
            %b Add a new user
            below, you will be guided as to what type of account you wish to create.

        .row-fluid.account-members
        - current_user.group.users.each do |u|
          .span2.account-member
            = image_tag 'icons/person-icon.png'
            %p
              Name: #{ u.profile.first_name }
              %br
              Role: #{ u.role?.humanize }

        - if current_user.group_users_remaining? > 0
          = link_to 'Add a new user', new_user_invitation_path, :class => 'btn btn-primary btn-large view invite-member'

  = render partial: 'shared/user_sidebar'