config/routes.rb
Gpathome::Application.routes.draw do

  # ActiveAdmin routes
  ActiveAdmin.routes(self)

  # devise setup for users
  # redirect after sign up
  # see: http://stackoverflow.com/questions/3827011/devise-custom-routes-and-login-pages
  devise_for :users, :controllers => { :registrations => 'registrations', :invitations => 'invitations' },
  :path => '',
  :path_names => { :sign_in => 'login', :sign_out => 'logout', :sign_up => 'sign_up' }

  # scope for devise routes
  devise_scope :user do
    match 'payment' => 'registrations#payment'
    match 'confirm' => 'registrations#confirm'
    match 'accepted' => 'invitations#accepted'
  end

  # on successful login
  namespace :user do
    root :to => 'dashboard#index'
  end

  resource :user do
    # user credits (top up etc)
    resources :credits do
      member do
        post 'top_up'
      end
    end
    # user account - what plan they are on, payments, expiration dates etc
    resource :account do
      member do
        get 'billing_details'
      end
      resource :password
      resource :notification
      resource :group
    end
  end

  get '/user/docustore' => 'docustore#index', :as => :docustore

  # path to upgrade current plan
  post '/plan/switch' => 'plans#switch', :as => :switch_plan

  # dependent profiles
  resources :profiles
  resources :medical_profiles

  # add the put method to /user/profile/edit for the user profiles page under the dashboard
  put '/user/account/password/edit', :as => :edit_user_account_password, :to => 'passwords#update'

  # check for new messages - via ajax
  get '/check_for_messages' => 'messages#check_for_messages'

  # user feedback
  resource :feedback

  # add the put method to /user/profile/edit for the user profiles page under the dashboard, do the same for medical profiles
  put '/profiles/:id/edit', :as => :edit_profile, :to => 'profiles#update'
  put '/medical_profiles/:id/edit', :as => :edit_medical_profile, :to => 'medical_profiles#update'

  # devise for admins
  #devise_for :admin_users, ActiveAdmin::Devise.config

  # assets
  resources :assets

  slugs = %w(take_a_tour our_service terms_and_conditions faqs typical_scenarios contact_us about_us)
  slugs.each do |slug|
    get "#{slug}_raw" => "static##{slug}", as: slug
  end

  get ':slug', to: 'pages#show',
    constraints: ->(req){ slugs.include? req.params[:slug] },
    as: :pages

  # main user dashbaord
  get 'dashboard' => 'dashboard#index'

  # static routes
  if SHOW_MEMBERSHIP_PLANS
    get 'membership_plans' => 'static#membership_plans'
  end
  post 'request_invite' => 'static#request_invite'

  resources :consultations do
    resources :messages
  end

  # payments - recurly
  namespace :payments do
    get 'success'
  end

  # currently routing to static / index
  root :to => 'static#index'

end

app/views/shared/_attachments.html.haml
= form_for @assets do |image|

  - if current_user.is_admin_or_gp?
    = image.hidden_field :attachable_type, :value => 'Consultation'
    = image.hidden_field :attachable_id, :value => @consultation.id
  - else
    = image.hidden_field :attachable_type, :value => 'Message'
    = image.hidden_field :attachable_id, :value => @message.id

  .file-attach-button
    %a{href:"#attach-files", class: 'btn btn-large attach-files'}
      Add Attachment
      = image.file_field :attachment

  %script{id:'template-upload', type:'text/x-tmpl'}
    .upload
      Uploading...
      .progress.progress-striped.active.progress-info
        .bar{style:'width: 0%'}

  .attachments
    - if current_user.is_admin_or_gp?
      - @consultation.assets.each do |asset|
        = render 'assets/asset', asset: asset

app/views/shared/_consultation_message.html.haml
- if can_create_consultation? == false
  %p.top-up-credits.alert.alert-message
    You have used up all your online credits, #{ link_to 'click here', user_credits_path } to top up.

- elsif current_user.medical_profile.read_and_understood == false
  %p.alert.alert-success
    = link_to 'Please click here', edit_medical_profile_path(current_user.medical_profile)
    to confirm you have read and updated your medical profile.

- else
  = link_to 'New Consultation', new_consultation_path, :class => 'new-consultation btn btn-primary btn-large view'

app/views/shared/_consultations.html.haml
- if consultations.any?
  %p.intro-paragraph Below is a list of recent consultations with your GP&hellip;
  - consultations.reverse.each do |consultation|
    .consultation.row-fluid{:class => mark_status(consultation)}
      .span2.small-doc
        = image_tag 'icons/small-doc-icon.png'
        %small Assigned to #{ assigned_to_who(consultation) }
      .span7.excerpt
        - if current_user.group.users.dependents
          %p
            Consultation on behalf of:
            %b= consultation.user.full_name
        %p
          Subject:
          %b= consultation.subject if consultation.subject
        %p= consultation.messages.last.message if consultation.messages.last
        %small From: #{ consultation.from? }
      .span3
        = link_to view_or_reply_text(consultation), consultation, :class => 'btn view'
- else
  %p.intro-paragraph No current consultations&hellip; Please click 'New Consultation'

app/views/shared/_error_messages.html.haml
- if error_messages.errors.any?
  .alert.alert-error.error
    %strong Sorry there were some problems with the form&hellip;
    %ul
      - error_messages.errors.full_messages.each do |msg|
        %li= msg
      
      

app/views/shared/_user_sidebar.html.haml
.span4.sidebar
  .profile-image
    = image_tag 'icons/person-icon.png'
    %p
      %b= current_user.profile.full_name
      %br
        Currently on the
        %b= current_user.group.plan.name
        plan
        %small.edit-profile= link_to 'Edit profile', edit_profile_path(current_user.profile)

  - if @consultation && @consultation.assets.any?
    .gp-attachments
      %h3 GP attachments
      %p Attachments from the GPs

      .attachments
        - @consultation.assets.each do |asset|
          = render 'assets/asset', asset: asset