config/routes.rb
Gpathome::Application.routes.draw do

  # ActiveAdmin routes
  ActiveAdmin.routes(self)

  # devise setup for users
  # redirect after sign up
  # see: http://stackoverflow.com/questions/3827011/devise-custom-routes-and-login-pages
  devise_for :users, :controllers => { :registrations => 'registrations', :invitations => 'invitations' },
  :path => '',
  :path_names => { :sign_in => 'login', :sign_out => 'logout', :sign_up => 'sign_up' }

  # scope for devise routes
  devise_scope :user do
    match 'payment' => 'registrations#payment'
    match 'confirm' => 'registrations#confirm'
    match 'accepted' => 'invitations#accepted'
  end

  # on successful login
  namespace :user do
    root :to => 'dashboard#index'
  end

  resource :user do
    # user credits (top up etc)
    resources :credits do
      member do
        post 'top_up'
      end
    end
    # user account - what plan they are on, payments, expiration dates etc
    resource :account do
      member do
        get 'billing_details'
      end
      resource :password
      resource :notification
      resource :group
    end
  end

  get '/user/docustore' => 'docustore#index', :as => :docustore

  # path to upgrade current plan
  post '/plan/switch' => 'plans#switch', :as => :switch_plan

  # dependent profiles
  resources :profiles
  resources :medical_profiles

  # add the put method to /user/profile/edit for the user profiles page under the dashboard
  put '/user/account/password/edit', :as => :edit_user_account_password, :to => 'passwords#update'

  # check for new messages - via ajax
  get '/check_for_messages' => 'messages#check_for_messages'

  # user feedback
  resource :feedback

  # add the put method to /user/profile/edit for the user profiles page under the dashboard, do the same for medical profiles
  put '/profiles/:id/edit', :as => :edit_profile, :to => 'profiles#update'
  put '/medical_profiles/:id/edit', :as => :edit_medical_profile, :to => 'medical_profiles#update'

  # devise for admins
  #devise_for :admin_users, ActiveAdmin::Devise.config

  # assets
  resources :assets

  slugs = %w(take_a_tour our_service terms_and_conditions faqs typical_scenarios contact_us about_us)
  slugs.each do |slug|
    get "#{slug}_raw" => "static##{slug}", as: slug
  end

  get ':slug', to: 'pages#show',
    constraints: ->(req){ slugs.include? req.params[:slug] },
    as: :pages

  # main user dashbaord
  get 'dashboard' => 'dashboard#index'

  # static routes
  if SHOW_MEMBERSHIP_PLANS
    get 'membership_plans' => 'static#membership_plans'
  end
  post 'request_invite' => 'static#request_invite'

  resources :consultations do
    resources :messages
  end

  # payments - recurly
  namespace :payments do
    get 'success'
  end

  # currently routing to static / index
  root :to => 'static#index'

end

app/models/asset.rb
class Asset < ActiveRecord::Base

  # polymorphic association so that other models can use this to store attachments
  belongs_to :attachable, :polymorphic => true

  has_many :taggings, :as => :taggable, :dependent => :destroy
  has_many :tags, :through => :taggings, :dependent => :destroy

  delegate :url, :to => :attachment

  attr_accessible :tag_list, :attachable_type, :attachable_id, :attachable_file_name, :attachment

  has_attached_file :attachment,
    :styles => {
      :thumb => '100x100#',
      :original => '600x600'
    }

  before_post_process :skip_file_type

  # TODO: Add file type / size / amount validations

  def file_type
    case self.attachment_content_type
    when /image/
      :image
    when /application/
      :file
    end
  end

  def doc_type
    case self.attachment_content_type
    when /pdf/
      :pdf
    else
      :msword
    end
  end

  # tags
  # TODO: Abstract this out into it's own module if it's going to be used elsewhere
  def tag_list=(names)
    self.tags = names.split(',').map do |n|
      Tag.where(name: n.strip).first_or_create!
    end
  end

  def tag_list
    tags.map(&:name).join(', ')
  end

  private

    # skip processing:
    # .pdf, .doc, .docx
    def skip_file_type
      ! %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document).include?(attachment_content_type)
    end

end

app/controllers/assets_controller.rb
class AssetsController < ActionController::Base

  before_filter :find_asset, except: [:create]

  def create
    if params[:attachable_id] && params[:attachable_type]
      params[:asset].merge!({
        attachable_id: params[:attachable_id],
        attachable_type: params[:attachable_type]
      })
    end
    @asset = Asset.create(params[:asset])
    render json: { status: 200, template: asset_template }
  end

  def edit
  end

  def update
    if @asset.update_attributes(params[:asset])
      flash[:success] = 'Tags updated successfully. Please close the window.'
    else
      flash[:error] = 'There was a problem updating the attachment'
    end
    @asset
  end

  def destroy
    @asset.destroy if destroyable?
  end

  private

  def find_asset
    @asset = Asset.find(params[:id])
  end

  def asset_template
    render_to_string '_asset', locals: { asset: @asset }
  end

  def destroyable?
    is_admin_attachment? || is_user_attachment?
  end

  def is_admin_attachment?
    @asset.attachable_type == 'Consultation' && current_user.is_admin_or_gp?
  end

  def is_user_attachment?
    @asset.attachable_type == 'Message' && !current_user.is_admin_or_gp?
  end
end

app/views/assets/_admin_asset_actions.html.haml
.admin-asset-actions
  = link_to 'Tag', edit_asset_path(asset), :remote => true, :class => 'edit-attachment'
  = link_to 'View', asset.url, :class => "view-attachment #{asset.file_type}-attachment"
  = link_to 'Delete', asset_path(asset), :remote => true, :method => :delete, :class => 'delete-attachment', :confirm => 'Are you sure you want to delete this attachment?'

app/views/assets/_asset.html.haml
.attachment{data: { id: asset.id }}
  - if current_user.is_admin_or_gp?
    = render "assets/admin_asset_actions", asset: asset

  = link_to asset.url, class: "view-attachment #{asset.file_type}-attachment", target: '_blank' do
    = render "assets/#{asset.file_type}", asset: asset, enlargement_allowed: false

    - unless current_user.is_admin_or_gp?
      = link_to 'X', asset_path(asset), remote: true, method: :delete, class: 'remove-attachment'

app/views/assets/_file.html.haml
%div{class: "file #{asset.doc_type}"}
  - if enlargement_allowed
    = link_to asset.url(:original), title: asset.attachment_file_name do
      .file-name= asset.attachment_file_name
  - else
    .file-name= truncate(asset.attachment_file_name, :length => 18)

app/views/assets/_image.html.haml
- if enlargement_allowed
  = link_to image_tag(asset.url(:thumb)), asset.url(:original), class: 'enlarge-attachment'
- else
  = image_tag asset.url :thumb

app/views/assets/_tag.html.haml
.tags_modal.modal
  .modal-header
    %h3 Tag File Attachment
  .modal-body
    %p Tags are seperated with commas. Use quotes for more than one word.
    = form_for @asset, remote: true do |f|
      = f.text_field :tag_list, placeholder: "lfts, bloods, 'medical report'"
      = f.submit 'Edit Tags'
  .modal-footer
    %a.btn{'data-dismiss' => 'modal', :href => '#'} Close

app/views/assets/destroy.js.erb
$('[data-id="<%= @asset.id %>"]')
  .fadeOut('slow', function() {
    $(this).remove();                                                 // remove the actual element
    $('#new_asset .attachments').trigger('update_attached_assets');   // update the array of attachment ids
  });